# Generated by Django 5.2 on 2025-11-22 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_internship_created_by_job_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='accounts.recruiter'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.recruiter'),
        ),
    ]
