# Generated by Django 5.2 on 2025-11-26 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='accounts.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.job')),
            ],
            options={
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
