# Generated by Django 5.2 on 2025-11-28 10:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_application'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('candidate', 'job')},
        ),
        migrations.AddField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='internship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.internship'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.candidate'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.job'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('candidate', 'internship'), ('candidate', 'job')},
        ),
    ]
