# Generated by Django 5.2 on 2025-12-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_resumeupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('course_start', models.IntegerField(blank=True, null=True)),
                ('course_end', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('career_status', models.CharField(blank=True, max_length=50)),
                ('linkedin', models.URLField(blank=True)),
                ('portfolio', models.URLField(blank=True)),
                ('about', models.TextField(blank=True)),
            ],
        ),
    ]
