# Generated by Django 5.2 on 2025-12-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_candidateprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='experiences',
            field=models.JSONField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='skills',
            field=models.JSONField(null=True, blank=True),
        ),
    ]
