# Generated by Django 5.2 on 2025-12-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_candidateprofile_experiences_candidateprofile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='experiences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
