# Generated by Django 5.2 on 2025-12-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_candidateprofile_experiences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
