# Generated by Django 5.2 on 2025-12-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_candidate_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='profile_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
