# Generated by Django 5.2 on 2025-12-18 16:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_internship_company_logo_alter_job_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='resumeupload',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
