const companies=[
    {"id":1,"name":"Accenture","logo":"https://logo.clearbit.com/accenture.com","company_size":"100k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":2,"name":"Acko","logo":"https://logo.clearbit.com/acko.com","company_size":"1k-5k","hiring_category":["Freshers","Experienced"]},
    {"id":3,"name":"Adobe","logo":"https://logo.clearbit.com/adobe.com","company_size":"25k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":4,"name":"ADP","logo":"https://logo.clearbit.com/adp.com","company_size":"60k+","hiring_category":["Freshers","Experienced"]},
    {"id":5,"name":"Airbus","logo":"https://logo.clearbit.com/airbus.com","company_size":"100k+","hiring_category":["Internship","Experienced"]},
    {"id":6,"name":"Airtel","logo":"https://logo.clearbit.com/airtel.in","company_size":"50k+","hiring_category":["Freshers","Experienced"]},
    {"id":7,"name":"Akamai","logo":"https://logo.clearbit.com/akamai.com","company_size":"8k+","hiring_category":["Freshers","Experienced"]},
    {"id":8,"name":"Akuna Capital","logo":"https://logo.clearbit.com/akunacapital.com","company_size":"1k+","hiring_category":["Internship","Experienced"]},
    {"id":9,"name":"Alation","logo":"https://logo.clearbit.com/alation.com","company_size":"1k-5k","hiring_category":["Freshers","Experienced"]},
    {"id":10,"name":"AlphaSense","logo":"https://logo.clearbit.com/alpha-sense.com","company_size":"1k+","hiring_category":["Internship","Experienced"]},
    {"id":11,"name":"Alphabet (Google)","logo":"https://logo.clearbit.com/google.com","company_size":"180k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":12,"name":"Alstom","logo":"https://logo.clearbit.com/alstom.com","company_size":"70k+","hiring_category":["Freshers","Experienced"]},
    {"id":13,"name":"AMD","logo":"https://logo.clearbit.com/amd.com","company_size":"25k+","hiring_category":["Freshers","Experienced"]},
    {"id":14,"name":"American Express","logo":"https://logo.clearbit.com/americanexpress.com","company_size":"60k+","hiring_category":["Internship","Experienced"]},
    {"id":15,"name":"Amadeus","logo":"https://logo.clearbit.com/amadeus.com","company_size":"20k+","hiring_category":["Freshers","Experienced"]},
    {"id":16,"name":"Amazon","logo":"https://logo.clearbit.com/amazon.com","company_size":"1M+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":17,"name":"Amdocs","logo":"https://logo.clearbit.com/amdocs.com","company_size":"30k+","hiring_category":["Freshers","Experienced"]},
    {"id":18,"name":"Amway","logo":"https://logo.clearbit.com/amwayglobal.com","company_size":"15k+","hiring_category":["Experienced"]},
    {"id":19,"name":"Ansys","logo":"https://logo.clearbit.com/ansys.com","company_size":"6k+","hiring_category":["Freshers","Experienced"]},
    {"id":20,"name":"Apisero","logo":"https://logo.clearbit.com/apisero.com","company_size":"5k+","hiring_category":["Freshers","Experienced"]},
    {"id":21,"name":"Apple","logo":"https://logo.clearbit.com/apple.com","company_size":"160k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":22,"name":"Applied Materials","logo":"https://logo.clearbit.com/appliedmaterials.com","company_size":"34k+","hiring_category":["Freshers","Experienced"]},
    {"id":23,"name":"Aptiv","logo":"https://logo.clearbit.com/aptiv.com","company_size":"150k+","hiring_category":["Freshers","Experienced"]},
    {"id":24,"name":"Arcesium","logo":"https://logo.clearbit.com/arcesium.com","company_size":"2k+","hiring_category":["Freshers","Experienced"]},
    {"id":25,"name":"Arista Networks","logo":"https://logo.clearbit.com/arista.com","company_size":"10k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":26,"name":"Asana","logo":"https://logo.clearbit.com/asana.com","company_size":"3k+","hiring_category":["Internship","Experienced"]},
    {"id":27,"name":"Ashok Leyland","logo":"https://logo.clearbit.com/ashokleyland.com","company_size":"12k+","hiring_category":["Freshers","Experienced"]},
    {"id":28,"name":"Asian Paints","logo":"https://logo.clearbit.com/asianpaints.com","company_size":"8k+","hiring_category":["Freshers","Experienced"]},
    {"id":29,"name":"Aspire Systems","logo":"https://logo.clearbit.com/aspiresys.com","company_size":"4k+","hiring_category":["Freshers","Experienced"]},
    {"id":30,"name":"Atkins","logo":"https://logo.clearbit.com/atkinsglobal.com","company_size":"20k+","hiring_category":["Experienced"]},
    {"id":31,"name":"Atlassian","logo":"https://logo.clearbit.com/atlassian.com","company_size":"10k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":32,"name":"Ather Energy","logo":"https://logo.clearbit.com/atherenergy.com","company_size":"3k+","hiring_category":["Freshers","Experienced"]},
    {"id":33,"name":"Athenahealth","logo":"https://logo.clearbit.com/athenahealth.com","company_size":"7k+","hiring_category":["Freshers","Experienced"]},
    {"id":34,"name":"Atos","logo":"https://logo.clearbit.com/atos.net","company_size":"100k+","hiring_category":["Freshers","Experienced"]},
    {"id":35,"name":"Automation Anywhere","logo":"https://logo.clearbit.com/automationanywhere.com","company_size":"3k+","hiring_category":["Experienced"]},
    {"id":36,"name":"Avast Software","logo":"https://logo.clearbit.com/avast.com","company_size":"2k+","hiring_category":["Experienced"]},
    {"id":37,"name":"Avaso Technology","logo":"https://logo.clearbit.com/avasotech.com","company_size":"1k+","hiring_category":["Experienced"]},
    {"id":38,"name":"Avaya","logo":"https://logo.clearbit.com/avaya.com","company_size":"8k+","hiring_category":["Freshers","Experienced"]},
    {"id":39,"name":"Avery Dennison","logo":"https://logo.clearbit.com/averydennison.com","company_size":"35k+","hiring_category":["Freshers","Experienced"]},
    {"id":40,"name":"Avis Budget Group","logo":"https://logo.clearbit.com/avisbudgetgroup.com","company_size":"25k+","hiring_category":["Experienced"]},
    {"id":41,"name":"Axtria","logo":"https://logo.clearbit.com/axtria.com","company_size":"2k+","hiring_category":["Freshers","Experienced"]},
    {"id":42,"name":"Axis Bank","logo":"https://logo.clearbit.com/axisbank.com","company_size":"80k+","hiring_category":["Freshers","Experienced"]},
    {"id":43,"name":"Bain & Company","logo":"https://logo.clearbit.com/bain.com","company_size":"15k+","hiring_category":["Freshers","Experienced"]},
    {"id":44,"name":"Bajaj Auto","logo":"https://logo.clearbit.com/bajajauto.com","company_size":"10k+","hiring_category":["Freshers","Experienced"]},
    {"id":45,"name":"Bajaj Finserv","logo":"https://logo.clearbit.com/bajajfinserv.in","company_size":"20k+","hiring_category":["Freshers","Experienced"]},
    {"id":46,"name":"Baker Hughes","logo":"https://logo.clearbit.com/bakerhughes.com","company_size":"50k+","hiring_category":["Freshers","Experienced"]},
    {"id":47,"name":"Bank of America","logo":"https://logo.clearbit.com/bankofamerica.com","company_size":"200k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":48,"name":"Barclays","logo":"https://logo.clearbit.com/barclays.com","company_size":"80k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":49,"name":"BASF","logo":"https://logo.clearbit.com/basf.com","company_size":"100k+","hiring_category":["Freshers","Experienced"]},
    {"id":50,"name":"BDO","logo":"https://logo.clearbit.com/bdo.global","company_size":"90k+","hiring_category":["Freshers","Experienced"]},
    {"id":51,"name":"Beko","logo":"https://logo.clearbit.com/beko.com","company_size":"30k+","hiring_category":["Experienced"]},
    {"id":52,"name":"Bentley Systems","logo":"https://logo.clearbit.com/bentley.com","company_size":"5k+","hiring_category":["Freshers","Experienced"]},
    {"id":53,"name":"Bharat Electronics Limited (BEL)","logo":"https://logo.clearbit.com/bel-india.in","company_size":"10k+","hiring_category":["Freshers","Experienced"]},
    {"id":54,"name":"Bharat Heavy Electricals Limited (BHEL)","logo":"https://logo.clearbit.com/bhel.com","company_size":"35k+","hiring_category":["Freshers","Experienced"]},
    {"id":55,"name":"Bharat Petroleum (BPCL)","logo":"https://logo.clearbit.com/bpcl.in","company_size":"12k+","hiring_category":["Freshers","Experienced"]},
    {"id":56,"name":"Bharti AXA","logo":"https://logo.clearbit.com/bharti-axagi.co.in","company_size":"8k+","hiring_category":["Freshers","Experienced"]},
    {"id":57,"name":"Biocon","logo":"https://logo.clearbit.com/biocon.com","company_size":"13k+","hiring_category":["Freshers","Experienced"]},
    {"id":58,"name":"BlackRock","logo":"https://logo.clearbit.com/blackrock.com","company_size":"20k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":59,"name":"Blackstone","logo":"https://logo.clearbit.com/blackstone.com","company_size":"5k+","hiring_category":["Experienced"]},
    {"id":60,"name":"Bloomberg","logo":"https://logo.clearbit.com/bloomberg.com","company_size":"25k+","hiring_category":["Internship","Experienced"]},
    {"id":61,"name":"Blue Yonder","logo":"https://logo.clearbit.com/blueyonder.com","company_size":"5k+","hiring_category":["Freshers","Experienced"]},
    {"id":62,"name":"BMC Software","logo":"https://logo.clearbit.com/bmc.com","company_size":"10k+","hiring_category":["Freshers","Experienced"]},
    {"id":63,"name":"Bosch","logo":"https://logo.clearbit.com/bosch.com","company_size":"400k+","hiring_category":["Freshers","Experienced"]},
    {"id":64,"name":"BP (British Petroleum)","logo":"https://logo.clearbit.com/bp.com","company_size":"70k+","hiring_category":["Freshers","Experienced"]},
    {"id":65,"name":"Bridgestone","logo":"https://logo.clearbit.com/bridgestone.com","company_size":"140k+","hiring_category":["Freshers","Experienced"]},
    {"id":66,"name":"Broadridge","logo":"https://logo.clearbit.com/broadridge.com","company_size":"14k+","hiring_category":["Freshers","Experienced"]},
    {"id":67,"name":"BYJU’S","logo":"https://logo.clearbit.com/byjus.com","company_size":"15k+","hiring_category":["Freshers","Experienced"]},
    {"id":68,"name":"Cadence","logo":"https://logo.clearbit.com/cadence.com","company_size":"10k+","hiring_category":["Freshers","Experienced"]},
    {"id":69,"name":"Capgemini","logo":"https://logo.clearbit.com/capgemini.com","company_size":"350k+","hiring_category":["Freshers","Experienced"]},
    {"id":70,"name":"Cars24","logo":"https://logo.clearbit.com/cars24.com","company_size":"5k+","hiring_category":["Freshers","Experienced"]},
    {"id":71,"name":"Caterpillar","logo":"https://logo.clearbit.com/caterpillar.com","company_size":"100k+","hiring_category":["Freshers","Experienced"]},
    {"id":72,"name":"CGI","logo":"https://logo.clearbit.com/cgi.com","company_size":"90k+","hiring_category":["Freshers","Experienced"]},
    {"id":73,"name":"Cisco","logo":"https://logo.clearbit.com/cisco.com","company_size":"80k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":74,"name":"Citi","logo":"https://logo.clearbit.com/citi.com","company_size":"200k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":75,"name":"Cognizant","logo":"https://logo.clearbit.com/cognizant.com","company_size":"340k+","hiring_category":["Freshers","Experienced"]},
    {"id":76,"name":"Coinbase","logo":"https://logo.clearbit.com/coinbase.com","company_size":"4k+","hiring_category":["Internship","Experienced"]},
    {"id":77,"name":"Colgate-Palmolive","logo":"https://logo.clearbit.com/colgatepalmolive.com","company_size":"35k+","hiring_category":["Freshers","Experienced"]},
    {"id":78,"name":"Commvault","logo":"https://logo.clearbit.com/commvault.com","company_size":"3k+","hiring_category":["Freshers","Experienced"]},
    {"id":79,"name":"Continental","logo":"https://logo.clearbit.com/continental.com","company_size":"200k+","hiring_category":["Freshers","Experienced"]},
    {"id":80,"name":"Cornerstone OnDemand","logo":"https://logo.clearbit.com/cornerstoneondemand.com","company_size":"4k+","hiring_category":["Experienced"]},
    {"id":81,"name":"Credit Suisse","logo":"https://logo.clearbit.com/credit-suisse.com","company_size":"48k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":82,"name":"CRED","logo":"https://logo.clearbit.com/cred.club","company_size":"1k+","hiring_category":["Experienced"]},
    {"id":83,"name":"CrowdStrike","logo":"https://logo.clearbit.com/crowdstrike.com","company_size":"7k+","hiring_category":["Internship","Experienced"]},
    {"id":84,"name":"Cyient","logo":"https://logo.clearbit.com/cyient.com","company_size":"15k+","hiring_category":["Freshers","Experienced"]},
    {"id":85,"name":"Cypress Semiconductor (Infineon)","logo":"https://logo.clearbit.com/infineon.com","company_size":"50k+","hiring_category":["Freshers","Experienced"]},
    {"id":86,"name":"Citrix (Cloud Software Group)","logo":"https://logo.clearbit.com/citrix.com","company_size":"10k+","hiring_category":["Experienced"]},
    {"id":87,"name":"Cloudera","logo":"https://logo.clearbit.com/cloudera.com","company_size":"3k+","hiring_category":["Experienced"]},
    {"id":88,"name":"CitiusTech","logo":"https://logo.clearbit.com/citiustech.com","company_size":"8k+","hiring_category":["Freshers","Experienced"]},
    {"id":89,"name":"CG Power","logo":"https://logo.clearbit.com/cgpower.com","company_size":"10k+","hiring_category":["Experienced"]},
    {"id":90,"name":"Chubb","logo":"https://logo.clearbit.com/chubb.com","company_size":"30k+","hiring_category":["Freshers","Experienced"]},
    {"id":91,"name":"Cleartax","logo":"https://logo.clearbit.com/cleartax.in","company_size":"1k+","hiring_category":["Freshers","Experienced"]},
    {"id":92,"name":"Cogoport","logo":"https://logo.clearbit.com/cogoport.com","company_size":"1k+","hiring_category":["Freshers","Experienced"]},
    {"id":93,"name":"Ciena","logo":"https://logo.clearbit.com/ciena.com","company_size":"8k+","hiring_category":["Freshers","Experienced"]},
    {"id":94,"name":"Curefit","logo":"https://logo.clearbit.com/cure.fit","company_size":"3k+","hiring_category":["Freshers","Experienced"]},
    {"id":95,"name":"Capillary Technologies","logo":"https://logo.clearbit.com/capillarytech.com","company_size":"1k+","hiring_category":["Freshers","Experienced"]},
    {"id":96,"name":"Canonical","logo":"https://logo.clearbit.com/canonical.com","company_size":"1k+","hiring_category":["Experienced"]},
    {"id":97,"name":"Chegg","logo":"https://logo.clearbit.com/chegg.com","company_size":"3k+","hiring_category":["Experienced"]},
    {"id":98,"name":"Clario","logo":"https://logo.clearbit.com/clario.com","company_size":"6k+","hiring_category":["Experienced"]},
    {"id":99,"name":"Cloudsek","logo":"https://logo.clearbit.com/cloudsek.com","company_size":"200+","hiring_category":["Freshers","Experienced"]},
    {"id":100,"name":"Cognex","logo":"https://logo.clearbit.com/cognex.com","company_size":"2k+","hiring_category":["Experienced"]},
    {"id":101,"name":"Databricks","logo":"https://logo.clearbit.com/databricks.com","company_size":"5k+","hiring_category":["Internship","Experienced"]},
    {"id":102,"name":"Dell","logo":"https://logo.clearbit.com/dell.com","company_size":"100k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":103,"name":"Deloitte","logo":"https://logo.clearbit.com/deloitte.com","company_size":"330k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":104,"name":"DHL","logo":"https://logo.clearbit.com/dhl.com","company_size":"380k+","hiring_category":["Experienced"]},
    {"id":105,"name":"Dropbox","logo":"https://logo.clearbit.com/dropbox.com","company_size":"3k+","hiring_category":["Experienced","Internship"]},
    {"id":106,"name":"DXC Technology","logo":"https://logo.clearbit.com/dxc.com","company_size":"130k+","hiring_category":["Experienced","Freshers"]},
    {"id":107,"name":"Dassault Systèmes","logo":"https://logo.clearbit.com/3ds.com","company_size":"20k+","hiring_category":["Freshers","Experienced"]},
    {"id":108,"name":"DocuSign","logo":"https://logo.clearbit.com/docusign.com","company_size":"6k+","hiring_category":["Experienced"]},
    {"id":109,"name":"Dream11","logo":"https://logo.clearbit.com/dream11.com","company_size":"2k+","hiring_category":["Freshers","Experienced"]},
    {"id":110,"name":"Darwinbox","logo":"https://logo.clearbit.com/darwinbox.com","company_size":"1k+","hiring_category":["Freshers","Experienced"]},
    {"id":111,"name":"DoorDash","logo":"https://logo.clearbit.com/doordash.com","company_size":"10k+","hiring_category":["Freshers","Experienced"]},
    {"id":112,"name":"Duolingo","logo":"https://logo.clearbit.com/duolingo.com","company_size":"3k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":113,"name":"Dynatrace","logo":"https://logo.clearbit.com/dynatrace.com","company_size":"6k+","hiring_category":["Experienced"]},
    {"id":114,"name":"D2iQ","logo":"https://logo.clearbit.com/d2iq.com","company_size":"1k+","hiring_category":["Experienced"]},
    {"id":115,"name":"Droom","logo":"https://logo.clearbit.com/droom.in","company_size":"800+","hiring_category":["Freshers","Experienced"]},
    {"id":116,"name":"Dun & Bradstreet","logo":"https://logo.clearbit.com/dnb.com","company_size":"5k+","hiring_category":["Experienced"]},
    {"id":117,"name":"DuPont","logo":"https://logo.clearbit.com/dupont.com","company_size":"34k+","hiring_category":["Experienced"]},
    {"id":118,"name":"Dassault Aviation","logo":"https://logo.clearbit.com/dassault-aviation.com","company_size":"12k+","hiring_category":["Experienced"]},
    {"id":119,"name":"Dropbox India","logo":"https://logo.clearbit.com/dropbox.com","company_size":"3k+","hiring_category":["Freshers","Experienced"]},
    {"id":120,"name":"DigitalOcean","logo":"https://logo.clearbit.com/digitalocean.com","company_size":"1k+","hiring_category":["Internship","Experienced"]},
    {"id":121,"name":"DBS Bank","logo":"https://logo.clearbit.com/dbs.com","company_size":"35k+","hiring_category":["Freshers","Experienced"]},
    {"id":122,"name":"DEVOPSGroup","logo":"https://logo.clearbit.com/devopsgroup.co.uk","company_size":"500+","hiring_category":["Experienced"]},
    {"id":123,"name":"DocuWare","logo":"https://logo.clearbit.com/docuware.com","company_size":"1k+","hiring_category":["Experienced"]},
    {"id":124,"name":"Dentsu","logo":"https://logo.clearbit.com/dentsu.com","company_size":"50k+","hiring_category":["Freshers","Experienced"]},
    {"id":125,"name":"DHL Supply Chain","logo":"https://logo.clearbit.com/dhl.com","company_size":"200k+","hiring_category":["Experienced"]},
    {"id":126,"name":"Devoteam","logo":"https://logo.clearbit.com/devoteam.com","company_size":"8k+","hiring_category":["Experienced","Freshers"]},
    {"id":127,"name":"Dr. Reddy’s Laboratories","logo":"https://logo.clearbit.com/drreddys.com","company_size":"20k+","hiring_category":["Experienced","Freshers"]},
    {"id":128,"name":"Deliveroo","logo":"https://logo.clearbit.com/deliveroo.co.uk","company_size":"3k+","hiring_category":["Freshers","Experienced"]},
    {"id":129,"name":"DP World","logo":"https://logo.clearbit.com/dpworld.com","company_size":"50k+","hiring_category":["Experienced"]},
    {"id":130,"name":"Datalight","logo":"https://logo.clearbit.com/datalight.com","company_size":"500+","hiring_category":["Experienced"]},
    {"id":131,"name":"Datamonitor","logo":"https://logo.clearbit.com/datamonitor.com","company_size":"200+","hiring_category":["Experienced"]},
    {"id":132,"name":"Dhiway","logo":"https://logo.clearbit.com/dhiway.com","company_size":"200+","hiring_category":["Freshers"]},
    {"id":133,"name":"Darktrace","logo":"https://logo.clearbit.com/darktrace.com","company_size":"1k+","hiring_category":["Experienced"]},
    {"id":134,"name":"Dixon Technologies","logo":"https://logo.clearbit.com/dixontech.com","company_size":"3k+","hiring_category":["Freshers","Experienced"]},
    {"id":135,"name":"Docker Inc","logo":"https://logo.clearbit.com/docker.com","company_size":"1k+","hiring_category":["Experienced"]},
    {"id":136,"name":"Dynatrace India","logo":"https://logo.clearbit.com/dynatrace.com","company_size":"6k+","hiring_category":["Freshers","Experienced"]},
    {"id":137,"name":"D.E. Shaw","logo":"https://logo.clearbit.com/deshaw.com","company_size":"6k+","hiring_category":["Experienced"]},
    {"id":138,"name":"Dassault Falcon Jet","logo":"https://logo.clearbit.com/dassaultfalcon.com","company_size":"1k+","hiring_category":["Experienced"]},
    {"id":139,"name":"Dataminr","logo":"https://logo.clearbit.com/dataminr.com","company_size":"1k+","hiring_category":["Experienced"]},
    {"id":140,"name":"DataStax","logo":"https://logo.clearbit.com/datastax.com","company_size":"1k+","hiring_category":["Experienced"]},
    {"id":141,"name":"DevExpress","logo":"https://logo.clearbit.com/devexpress.com","company_size":"500+","hiring_category":["Experienced"]},
    {"id":142,"name":"Dialog Semiconductor","logo":"https://logo.clearbit.com/dialog-semiconductor.com","company_size":"1k+","hiring_category":["Experienced"]},
    {"id":143,"name":"Domo","logo":"https://logo.clearbit.com/domo.com","company_size":"500+","hiring_category":["Experienced"]},
    {"id":144,"name":"DuckDuckGo","logo":"https://logo.clearbit.com/duckduckgo.com","company_size":"200+","hiring_category":["Experienced"]},
    {"id":145,"name":"DuPont","logo":"https://logo.clearbit.com/dupont.com","company_size":"30k+","hiring_category":["Experienced"]},
    {"id":146,"name":"Dropbox Business","logo":"https://logo.clearbit.com/dropbox.com","company_size":"3k+","hiring_category":["Freshers","Experienced"]},
    {"id":147,"name":"DataRobot","logo":"https://logo.clearbit.com/datarobot.com","company_size":"1k+","hiring_category":["Experienced"]},
    {"id":148,"name":"Digital Guardian","logo":"https://logo.clearbit.com/digitalguardian.com","company_size":"500+","hiring_category":["Experienced"]},
    {"id":149,"name":"Dassault Systems India","logo":"https://logo.clearbit.com/3ds.com","company_size":"2k+","hiring_category":["Freshers","Experienced"]},
    {"id":150,"name":"Dell Boomi","logo":"https://logo.clearbit.com/boomi.com","company_size":"1k+","hiring_category":["Freshers","Experienced"]},
    {"id":151,"name":"eBay","logo":"https://logo.clearbit.com/ebay.com","company_size":"30k+","hiring_category":["Freshers","Experienced"]},
    {"id":152,"name":"Ericsson","logo":"https://logo.clearbit.com/ericsson.com","company_size":"100k+","hiring_category":["Freshers","Experienced"]},
    {"id":153,"name":"Expedia Group","logo":"https://logo.clearbit.com/expedia.com","company_size":"25k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":154,"name":"EY (Ernst & Young)","logo":"https://logo.clearbit.com/ey.com","company_size":"350k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":155,"name":"Electronic Arts","logo":"https://logo.clearbit.com/ea.com","company_size":"13k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":156,"name":"Equinix","logo":"https://logo.clearbit.com/equinix.com","company_size":"12k+","hiring_category":["Experienced"]},
    {"id":157,"name":"EPAM Systems","logo":"https://logo.clearbit.com/epam.com","company_size":"60k+","hiring_category":["Freshers","Experienced"]},
    {"id":158,"name":"Elastic","logo":"https://logo.clearbit.com/elastic.co","company_size":"3k+","hiring_category":["Experienced"]},
    {"id":159,"name":"Esri","logo":"https://logo.clearbit.com/esri.com","company_size":"5k+","hiring_category":["Experienced","Internship"]},
    {"id":160,"name":"Eaton","logo":"https://logo.clearbit.com/eaton.com","company_size":"90k+","hiring_category":["Freshers","Experienced"]},
    {"id":161,"name":"Eurofins","logo":"https://logo.clearbit.com/eurofins.com","company_size":"70k+","hiring_category":["Freshers","Experienced"]},
    {"id":162,"name":"Edelman","logo":"https://logo.clearbit.com/edelman.com","company_size":"6k+","hiring_category":["Freshers","Experienced"]},
    {"id":163,"name":"Endurance International Group","logo":"https://logo.clearbit.com/endurance.com","company_size":"4k+","hiring_category":["Experienced"]},
    {"id":164,"name":"Envoy","logo":"https://logo.clearbit.com/envoy.com","company_size":"500+","hiring_category":["Experienced"]},
    {"id":165,"name":"Engie","logo":"https://logo.clearbit.com/engie.com","company_size":"170k+","hiring_category":["Experienced","Freshers"]},
    {"id":166,"name":"Euroclear","logo":"https://logo.clearbit.com/euroclear.com","company_size":"4k+","hiring_category":["Experienced","Internship"]},
    {"id":167,"name":"Eli Lilly","logo":"https://logo.clearbit.com/lilly.com","company_size":"40k+","hiring_category":["Freshers","Experienced"]},
    {"id":168,"name":"Elex Media","logo":"https://logo.clearbit.com/elex.com","company_size":"1k+","hiring_category":["Experienced"]},
    {"id":169,"name":"Epsilon","logo":"https://logo.clearbit.com/emea.epsilon.com","company_size":"8k+","hiring_category":["Experienced"]},
    {"id":170,"name":"Entertainment Partners","logo":"https://logo.clearbit.com/ep.com","company_size":"2k+","hiring_category":["Experienced"]},
    {"id":171,"name":"Eurostar","logo":"https://logo.clearbit.com/eurostar.com","company_size":"1k+","hiring_category":["Experienced"]},
    {"id":172,"name":"E2Open","logo":"https://logo.clearbit.com/e2open.com","company_size":"3k+","hiring_category":["Experienced"]},
    {"id":173,"name":"Emerson","logo":"https://logo.clearbit.com/emerson.com","company_size":"85k+","hiring_category":["Freshers","Experienced"]},
    {"id":174,"name":"Evernorth","logo":"https://logo.clearbit.com/evernorth.com","company_size":"10k+","hiring_category":["Experienced"]},
    {"id":175,"name":"Eventbrite","logo":"https://logo.clearbit.com/eventbrite.com","company_size":"1k+","hiring_category":["Experienced","Internship"]},
    {"id":176,"name":"ET Money","logo":"https://logo.clearbit.com/etmoney.com","company_size":"500+","hiring_category":["Freshers","Experienced"]},
    {"id":177,"name":"Eurotech","logo":"https://logo.clearbit.com/eurotech.com","company_size":"500+","hiring_category":["Experienced"]},
    {"id":178,"name":"Eros Now","logo":"https://logo.clearbit.com/erosnow.com","company_size":"500+","hiring_category":["Experienced"]},
    {"id":179,"name":"ETSY","logo":"https://logo.clearbit.com/etsy.com","company_size":"3k+","hiring_category":["Experienced","Internship"]},
    {"id":180,"name":"Equifax","logo":"https://logo.clearbit.com/equifax.com","company_size":"12k+","hiring_category":["Experienced","Freshers"]},
    {"id":181,"name":"Emaar","logo":"https://logo.clearbit.com/emaar.com","company_size":"10k+","hiring_category":["Experienced"]},
    {"id":182,"name":"Eicher Motors","logo":"https://logo.clearbit.com/eichermotors.com","company_size":"5k+","hiring_category":["Freshers","Experienced"]},
    {"id":183,"name":"EssilorLuxottica","logo":"https://logo.clearbit.com/essilorluxottica.com","company_size":"180k+","hiring_category":["Experienced"]},
    {"id":184,"name":"eInfochips","logo":"https://logo.clearbit.com/einfochips.com","company_size":"3k+","hiring_category":["Freshers","Experienced"]},
    {"id":185,"name":"Edelweiss","logo":"https://logo.clearbit.com/edelweiss.in","company_size":"10k+","hiring_category":["Freshers","Experienced"]},
    {"id":186,"name":"EchoStar","logo":"https://logo.clearbit.com/echostar.com","company_size":"5k+","hiring_category":["Experienced"]},
    {"id":187,"name":"Everyday Health","logo":"https://logo.clearbit.com/everydayhealth.com","company_size":"1k+","hiring_category":["Experienced"]},
    {"id":188,"name":"Elgi Equipments","logo":"https://logo.clearbit.com/elgi.com","company_size":"2k+","hiring_category":["Freshers","Experienced"]},
    {"id":189,"name":"Eros International","logo":"https://logo.clearbit.com/erosintl.com","company_size":"1k+","hiring_category":["Experienced"]},
    {"id":190,"name":"Exide Industries","logo":"https://logo.clearbit.com/exideindustries.com","company_size":"5k+","hiring_category":["Freshers","Experienced"]},
    {"id":191,"name":"Exotel","logo":"https://logo.clearbit.com/exotel.com","company_size":"500+","hiring_category":["Freshers","Experienced"]},
    {"id":192,"name":"Exl Service","logo":"https://logo.clearbit.com/exlservice.com","company_size":"50k+","hiring_category":["Freshers","Experienced"]},
    {"id":193,"name":"Eko","logo":"https://logo.clearbit.com/eko.in","company_size":"200+","hiring_category":["Freshers","Experienced"]},
    {"id":194,"name":"Eurovia","logo":"https://logo.clearbit.com/eurovia.com","company_size":"40k+","hiring_category":["Experienced"]},
    {"id":195,"name":"Ergomed","logo":"https://logo.clearbit.com/ergomedplc.com","company_size":"500+","hiring_category":["Experienced"]},
    {"id":196,"name":"EagleView","logo":"https://logo.clearbit.com/eagleview.com","company_size":"800+","hiring_category":["Experienced"]},
    {"id":197,"name":"Etsy India","logo":"https://logo.clearbit.com/etsy.com","company_size":"200+","hiring_category":["Experienced"]},
    {"id":198,"name":"Evernote","logo":"https://logo.clearbit.com/evernote.com","company_size":"500+","hiring_category":["Experienced","Internship"]},
    {"id":199,"name":"Edureka","logo":"https://logo.clearbit.com/edureka.co","company_size":"600+","hiring_category":["Freshers","Experienced"]},
    {"id":200,"name":"E2E Networks","logo":"https://logo.clearbit.com/e2enetworks.com","company_size":"300+","hiring_category":["Freshers","Experienced"]},
    {"id":201,"name":"Facebook (Meta)","logo":"https://logo.clearbit.com/meta.com","company_size":"90k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":202,"name":"Flipkart","logo":"https://logo.clearbit.com/flipkart.com","company_size":"30k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":203,"name":"Foxconn","logo":"https://logo.clearbit.com/foxconn.com","company_size":"800k+","hiring_category":["Freshers","Experienced"]},
    {"id":204,"name":"Fidelity Investments","logo":"https://logo.clearbit.com/fidelity.com","company_size":"70k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":205,"name":"Fiserv","logo":"https://logo.clearbit.com/fiserv.com","company_size":"40k+","hiring_category":["Freshers","Experienced"]},
    {"id":206,"name":"Ford","logo":"https://logo.clearbit.com/ford.com","company_size":"170k+","hiring_category":["Freshers","Experienced"]},
    {"id":207,"name":"Fortinet","logo":"https://logo.clearbit.com/fortinet.com","company_size":"12k+","hiring_category":["Experienced","Internship"]},
    {"id":208,"name":"Figma","logo":"https://logo.clearbit.com/figma.com","company_size":"1k+","hiring_category":["Internship","Experienced"]},
    {"id":209,"name":"Freshworks","logo":"https://logo.clearbit.com/freshworks.com","company_size":"6k+","hiring_category":["Freshers","Experienced"]},
    {"id":210,"name":"F5 Networks","logo":"https://logo.clearbit.com/f5.com","company_size":"6k+","hiring_category":["Experienced","Internship"]},
    {"id":211,"name":"Freudenberg","logo":"https://logo.clearbit.com/freudenberg.com","company_size":"50k+","hiring_category":["Experienced","Freshers"]},
    {"id":212,"name":"Faurecia","logo":"https://logo.clearbit.com/faurecia.com","company_size":"110k+","hiring_category":["Freshers","Experienced"]},
    {"id":213,"name":"FirstSource","logo":"https://logo.clearbit.com/firstsource.com","company_size":"26k+","hiring_category":["Freshers","Experienced"]},
    {"id":214,"name":"FICO","logo":"https://logo.clearbit.com/fico.com","company_size":"4k+","hiring_category":["Experienced","Internship"]},
    {"id":215,"name":"Flutterwave","logo":"https://logo.clearbit.com/flutterwave.com","company_size":"800+","hiring_category":["Experienced"]},
    {"id":216,"name":"FarEye","logo":"https://logo.clearbit.com/getfareye.com","company_size":"400+","hiring_category":["Freshers","Experienced"]},
    {"id":217,"name":"FarmRise","logo":"https://logo.clearbit.com/farmrise.com","company_size":"200+","hiring_category":["Freshers","Experienced"]},
    {"id":218,"name":"Fractal Analytics","logo":"https://logo.clearbit.com/fractal.ai","company_size":"4k+","hiring_category":["Freshers","Experienced"]},
    {"id":219,"name":"Fosun","logo":"https://logo.clearbit.com/fosun.com","company_size":"70k+","hiring_category":["Experienced"]},
    {"id":220,"name":"Finastra","logo":"https://logo.clearbit.com/finastra.com","company_size":"10k+","hiring_category":["Freshers","Experienced"]},
    {"id":221,"name":"Flywire","logo":"https://logo.clearbit.com/flywire.com","company_size":"600+","hiring_category":["Experienced","Internship"]},
    {"id":222,"name":"Fynd","logo":"https://logo.clearbit.com/fynd.com","company_size":"500+","hiring_category":["Freshers","Experienced"]},
    {"id":223,"name":"Fortune Brands","logo":"https://logo.clearbit.com/fortunebrands.com","company_size":"10k+","hiring_category":["Experienced"]},
    {"id":224,"name":"Fisker","logo":"https://logo.clearbit.com/fiskerinc.com","company_size":"2k+","hiring_category":["Experienced","Internship"]},
    {"id":225,"name":"Flex","logo":"https://logo.clearbit.com/flex.com","company_size":"170k+","hiring_category":["Freshers","Experienced"]},
    {"id":226,"name":"Flink","logo":"https://logo.clearbit.com/goflink.com","company_size":"10k+","hiring_category":["Experienced"]},
    {"id":227,"name":"Fastrack (Titan)","logo":"https://logo.clearbit.com/fastrack.in","company_size":"2k+","hiring_category":["Freshers","Experienced"]},
    {"id":228,"name":"FireEye (Trellix)","logo":"https://logo.clearbit.com/trellix.com","company_size":"5k+","hiring_category":["Experienced"]},
    {"id":229,"name":"Furukawa Electric","logo":"https://logo.clearbit.com/furukawa.co.jp","company_size":"50k+","hiring_category":["Experienced","Freshers"]},
    {"id":230,"name":"Forescout","logo":"https://logo.clearbit.com/forescout.com","company_size":"1.5k+","hiring_category":["Experienced"]},
    {"id":231,"name":"Freecharge","logo":"https://logo.clearbit.com/freecharge.in","company_size":"300+","hiring_category":["Freshers","Experienced"]},
    {"id":232,"name":"Flyos","logo":"https://logo.clearbit.com/flyos.com","company_size":"100+","hiring_category":["Experienced"]},
    {"id":233,"name":"Fortis Healthcare","logo":"https://logo.clearbit.com/fortishealthcare.com","company_size":"23k+","hiring_category":["Freshers","Experienced"]},
    {"id":234,"name":"FuboTV","logo":"https://logo.clearbit.com/fubo.tv","company_size":"500+","hiring_category":["Experienced"]},
    {"id":235,"name":"Fetch Rewards","logo":"https://logo.clearbit.com/fetch.com","company_size":"1k+","hiring_category":["Internship","Experienced"]},
    {"id":236,"name":"Fiverr","logo":"https://logo.clearbit.com/fiverr.com","company_size":"1k+","hiring_category":["Experienced"]},
    {"id":237,"name":"Flock","logo":"https://logo.clearbit.com/flock.com","company_size":"200+","hiring_category":["Freshers","Experienced"]},
    {"id":238,"name":"Filevine","logo":"https://logo.clearbit.com/filevine.com","company_size":"500+","hiring_category":["Experienced"]},
    {"id":239,"name":"FullContact","logo":"https://logo.clearbit.com/fullcontact.com","company_size":"300+","hiring_category":["Experienced","Internship"]},
    {"id":240,"name":"Funimation","logo":"https://logo.clearbit.com/funimation.com","company_size":"700+","hiring_category":["Experienced"]},
    {"id":241,"name":"FTI Consulting","logo":"https://logo.clearbit.com/fticonsulting.com","company_size":"7k+","hiring_category":["Experienced","Freshers"]},
    {"id":242,"name":"Future Group","logo":"https://logo.clearbit.com/futuregroup.in","company_size":"50k+","hiring_category":["Freshers","Experienced"]},
    {"id":243,"name":"FirstCry","logo":"https://logo.clearbit.com/firstcry.com","company_size":"10k+","hiring_category":["Freshers","Experienced"]},
    {"id":244,"name":"Fynd Academy","logo":"https://logo.clearbit.com/fynd.com","company_size":"200+","hiring_category":["Freshers"]},
    {"id":245,"name":"FinBox","logo":"https://logo.clearbit.com/finbox.in","company_size":"200+","hiring_category":["Freshers","Experienced"]},
    {"id":246,"name":"Fibe (formerly EarlySalary)","logo":"https://logo.clearbit.com/fibe.in","company_size":"500+","hiring_category":["Freshers","Experienced"]},
    {"id":247,"name":"Fortis Advisors","logo":"https://logo.clearbit.com/fortisadvisors.com","company_size":"200+","hiring_category":["Experienced"]},
    {"id":248,"name":"Foodpanda","logo":"https://logo.clearbit.com/foodpanda.com","company_size":"5k+","hiring_category":["Experienced"]},
    {"id":249,"name":"Falabella","logo":"https://logo.clearbit.com/falabella.com","company_size":"100k+","hiring_category":["Experienced"]},
    {"id":250,"name":"Fab Hotels","logo":"https://logo.clearbit.com/fabhotels.com","company_size":"1k+","hiring_category":["Freshers","Experienced"]},
    {"id":251,"name":"Google","logo":"https://logo.clearbit.com/google.com","company_size":"190k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":252,"name":"Goldman Sachs","logo":"https://logo.clearbit.com/goldmansachs.com","company_size":"45k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":253,"name":"General Electric (GE)","logo":"https://logo.clearbit.com/ge.com","company_size":"200k+","hiring_category":["Freshers","Experienced"]},
    {"id":254,"name":"Genpact","logo":"https://logo.clearbit.com/genpact.com","company_size":"115k+","hiring_category":["Freshers","Experienced"]},
    {"id":255,"name":"Gartner","logo":"https://logo.clearbit.com/gartner.com","company_size":"20k+","hiring_category":["Internship","Experienced"]},
    {"id":256,"name":"GitHub","logo":"https://logo.clearbit.com/github.com","company_size":"3k+","hiring_category":["Experienced","Internship"]},
    {"id":257,"name":"GitLab","logo":"https://logo.clearbit.com/gitlab.com","company_size":"2k+","hiring_category":["Experienced"]},
    {"id":258,"name":"GSK","logo":"https://logo.clearbit.com/gsk.com","company_size":"100k+","hiring_category":["Freshers","Experienced"]},
    {"id":259,"name":"Gojek","logo":"https://logo.clearbit.com/gojek.com","company_size":"10k+","hiring_category":["Experienced","Internship"]},
    {"id":260,"name":"GlobalLogic","logo":"https://logo.clearbit.com/globallogic.com","company_size":"30k+","hiring_category":["Freshers","Experienced"]},
    {"id":261,"name":"GreyOrange","logo":"https://logo.clearbit.com/greyorange.com","company_size":"2k+","hiring_category":["Freshers","Experienced"]},
    {"id":262,"name":"Grid Dynamics","logo":"https://logo.clearbit.com/griddynamics.com","company_size":"4k+","hiring_category":["Freshers","Experienced"]},
    {"id":263,"name":"Gravitas AI","logo":"https://logo.clearbit.com/gravitas.ai","company_size":"100+","hiring_category":["Freshers","Experienced"]},
    {"id":264,"name":"GlobalFoundries","logo":"https://logo.clearbit.com/globalfoundries.com","company_size":"15k+","hiring_category":["Freshers","Experienced"]},
    {"id":265,"name":"Grofers (Blinkit)","logo":"https://logo.clearbit.com/blinkit.com","company_size":"10k+","hiring_category":["Freshers","Experienced"]},
    {"id":266,"name":"GoDaddy","logo":"https://logo.clearbit.com/godaddy.com","company_size":"7k+","hiring_category":["Experienced"]},
    {"id":267,"name":"Gree Electric","logo":"https://logo.clearbit.com/gree.com","company_size":"80k+","hiring_category":["Experienced"]},
    {"id":268,"name":"Garmin","logo":"https://logo.clearbit.com/garmin.com","company_size":"19k+","hiring_category":["Freshers","Experienced"]},
    {"id":269,"name":"GalaxE Solutions","logo":"https://logo.clearbit.com/galaxe.com","company_size":"2k+","hiring_category":["Freshers","Experienced"]},
    {"id":270,"name":"Guidewire","logo":"https://logo.clearbit.com/guidewire.com","company_size":"3k+","hiring_category":["Experienced","Internship"]},
    {"id":271,"name":"Gainsight","logo":"https://logo.clearbit.com/gainsight.com","company_size":"1.5k+","hiring_category":["Freshers","Experienced"]},
    {"id":272,"name":"GE Healthcare","logo":"https://logo.clearbit.com/gehc.co","company_size":"50k+","hiring_category":["Freshers","Experienced"]},
    {"id":273,"name":"GE Vernova","logo":"https://logo.clearbit.com/ge.com","company_size":"75k+","hiring_category":["Freshers","Experienced"]},
    {"id":274,"name":"Glenmark Pharma","logo":"https://logo.clearbit.com/glenmarkpharma.com","company_size":"15k+","hiring_category":["Freshers","Experienced"]},
    {"id":275,"name":"Gameloft","logo":"https://logo.clearbit.com/gameloft.com","company_size":"4k+","hiring_category":["Freshers","Experienced"]},
    {"id":276,"name":"Glu Mobile","logo":"https://logo.clearbit.com/glu.com","company_size":"800+","hiring_category":["Experienced","Internship"]},
    {"id":277,"name":"Glassdoor","logo":"https://logo.clearbit.com/glassdoor.com","company_size":"1k+","hiring_category":["Experienced"]},
    {"id":278,"name":"GoPro","logo":"https://logo.clearbit.com/gopro.com","company_size":"1k+","hiring_category":["Experienced","Internship"]},
    {"id":279,"name":"Gupshup","logo":"https://logo.clearbit.com/gupshup.io","company_size":"1.2k+","hiring_category":["Freshers","Experienced"]},
    {"id":280,"name":"Gameskraft","logo":"https://logo.clearbit.com/gameskraft.com","company_size":"700+","hiring_category":["Freshers","Experienced"]},
    {"id":281,"name":"Groww","logo":"https://logo.clearbit.com/groww.in","company_size":"3k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":282,"name":"Google Pay","logo":"https://logo.clearbit.com/google.com","company_size":"Segment","hiring_category":["Experienced","Internship"]},
    {"id":283,"name":"Gati Logistics","logo":"https://logo.clearbit.com/gati.com","company_size":"5k+","hiring_category":["Freshers","Experienced"]},
    {"id":284,"name":"Greaves Cotton","logo":"https://logo.clearbit.com/greavescotton.com","company_size":"3k+","hiring_category":["Freshers","Experienced"]},
    {"id":285,"name":"Grofers Engineering","logo":"https://logo.clearbit.com/blinkit.com","company_size":"Engineering Team","hiring_category":["Freshers","Experienced"]},
    {"id":286,"name":"Greenwave Systems","logo":"https://logo.clearbit.com/greenwavesys.com","company_size":"500+","hiring_category":["Experienced"]},
    {"id":287,"name":"Guidesly","logo":"https://logo.clearbit.com/guidesly.com","company_size":"SME","hiring_category":["Internship","Experienced"]},
    {"id":288,"name":"Gullak","logo":"https://logo.clearbit.com/gullak.money","company_size":"300+","hiring_category":["Freshers","Experienced"]},
    {"id":289,"name":"Grammarly","logo":"https://logo.clearbit.com/grammarly.com","company_size":"1k+","hiring_category":["Internship","Experienced"]},
    {"id":290,"name":"GlowRoad (Amazon)","logo":"https://logo.clearbit.com/glowroad.com","company_size":"1k+","hiring_category":["Freshers","Experienced"]},
    {"id":291,"name":"Game24x7","logo":"https://logo.clearbit.com/play.games24x7.com","company_size":"1k+","hiring_category":["Freshers","Experienced"]},
    {"id":292,"name":"Gravitas Finance","logo":"https://logo.clearbit.com/gravitasfinance.com","company_size":"500+","hiring_category":["Experienced"]},
    {"id":293,"name":"Goodera","logo":"https://logo.clearbit.com/goodera.com","company_size":"400+","hiring_category":["Freshers","Experienced"]},
    {"id":294,"name":"Great Learning","logo":"https://logo.clearbit.com/greatlearning.in","company_size":"1k+","hiring_category":["Freshers","Experienced"]},
    {"id":295,"name":"Gainsight PX","logo":"https://logo.clearbit.com/gainsight.com","company_size":"Segment","hiring_category":["Experienced"]},
    {"id":296,"name":"GlobalStep","logo":"https://logo.clearbit.com/globalstep.com","company_size":"3k+","hiring_category":["Freshers","Experienced"]},
    {"id":297,"name":"Grandstream","logo":"https://logo.clearbit.com/grandstream.com","company_size":"500+","hiring_category":["Experienced"]},
    {"id":298,"name":"GMR Group","logo":"https://logo.clearbit.com/gmrgroup.in","company_size":"12k+","hiring_category":["Freshers","Experienced"]},
    {"id":299,"name":"GoMechanic","logo":"https://logo.clearbit.com/gomechanic.in","company_size":"600+","hiring_category":["Experienced"]},
    {"id":300,"name":"Gameberry Labs","logo":"https://logo.clearbit.com/gameberrylabs.com","company_size":"200+","hiring_category":["Freshers","Experienced"]},
    {"id":301,"name":"HCL Technologies","logo":"https://logo.clearbit.com/hcltech.com","company_size":"225k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":302,"name":"HP","logo":"https://logo.clearbit.com/hp.com","company_size":"58k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":303,"name":"Honeywell","logo":"https://logo.clearbit.com/honeywell.com","company_size":"98k+","hiring_category":["Experienced","Internship","Freshers"]},
    {"id":304,"name":"Huawei","logo":"https://logo.clearbit.com/huawei.com","company_size":"195k+","hiring_category":["Experienced","Internship"]},
    {"id":305,"name":"Harman International","logo":"https://logo.clearbit.com/harman.com","company_size":"30k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":306,"name":"Hitachi","logo":"https://logo.clearbit.com/hitachi.com","company_size":"320k+","hiring_category":["Experienced","Internship","Freshers"]},
    {"id":307,"name":"HDFC Bank","logo":"https://logo.clearbit.com/hdfcbank.com","company_size":"1.7M+","hiring_category":["Freshers","Experienced"]},
    {"id":308,"name":"Hotstar","logo":"https://logo.clearbit.com/hotstar.com","company_size":"3k+","hiring_category":["Internship","Experienced"]},
    {"id":309,"name":"Hexaware Technologies","logo":"https://logo.clearbit.com/hexaware.com","company_size":"27k+","hiring_category":["Freshers","Experienced"]},
    {"id":310,"name":"HERE Technologies","logo":"https://logo.clearbit.com/here.com","company_size":"10k+","hiring_category":["Experienced","Internship","Freshers"]},
    {"id":311,"name":"Happiest Minds","logo":"https://logo.clearbit.com/happiestminds.com","company_size":"5k+","hiring_category":["Freshers","Experienced"]},
    {"id":312,"name":"Hyatt Hotels","logo":"https://logo.clearbit.com/hyatt.com","company_size":"100k+","hiring_category":["Freshers","Experienced"]},
    {"id":313,"name":"Hilton","logo":"https://logo.clearbit.com/hilton.com","company_size":"150k+","hiring_category":["Freshers","Experienced"]},
    {"id":314,"name":"Hero MotoCorp","logo":"https://logo.clearbit.com/heromotocorp.com","company_size":"9k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":315,"name":"Hindustan Unilever","logo":"https://logo.clearbit.com/hul.co.in","company_size":"21k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":316,"name":"Housing.com","logo":"https://logo.clearbit.com/housing.com","company_size":"1k+","hiring_category":["Experienced","Freshers"]},
    {"id":317,"name":"HealthifyMe","logo":"https://logo.clearbit.com/healthifyme.com","company_size":"500+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":318,"name":"Headout","logo":"https://logo.clearbit.com/headout.com","company_size":"300+","hiring_category":["Experienced","Internship"]},
    {"id":319,"name":"HackerEarth","logo":"https://logo.clearbit.com/hackerearth.com","company_size":"300+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":320,"name":"Hootsuite","logo":"https://logo.clearbit.com/hootsuite.com","company_size":"1k+","hiring_category":["Experienced","Internship"]},
    {"id":321,"name":"JPMorgan Chase","logo":"https://logo.clearbit.com/jpmorganchase.com","company_size":"300k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":322,"name":"Johnson & Johnson","logo":"https://logo.clearbit.com/jnj.com","company_size":"150k+","hiring_category":["Experienced","Freshers","Internship"]},
    {"id":323,"name":"Justdial","logo":"https://logo.clearbit.com/justdial.com","company_size":"12k+","hiring_category":["Freshers","Experienced"]},
    {"id":324,"name":"Jacobs Engineering","logo":"https://logo.clearbit.com/jacobs.com","company_size":"60k+","hiring_category":["Experienced","Internship"]},
    {"id":325,"name":"JLL (Jones Lang LaSalle)","logo":"https://logo.clearbit.com/jll.com","company_size":"100k+","hiring_category":["Freshers","Experienced"]},
    {"id":326,"name":"Juniper Networks","logo":"https://logo.clearbit.com/juniper.net","company_size":"10k+","hiring_category":["Experienced","Internship","Freshers"]},
    {"id":327,"name":"Jet Airways","logo":"https://logo.clearbit.com/jetairways.com","company_size":"12k+","hiring_category":["Experienced","Freshers"]},
    {"id":328,"name":"Jio Platforms","logo":"https://logo.clearbit.com/jio.com","company_size":"20k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":329,"name":"Juspay","logo":"https://logo.clearbit.com/juspay.in","company_size":"500+","hiring_category":["Internship","Experienced","Freshers"]},
    {"id":330,"name":"Jupiter Money","logo":"https://logo.clearbit.com/jupiter.money","company_size":"600+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":331,"name":"Jubilant FoodWorks","logo":"https://logo.clearbit.com/jubilantfoodworks.com","company_size":"35k+","hiring_category":["Freshers","Experienced"]},
    {"id":332,"name":"Jungleworks","logo":"https://logo.clearbit.com/jungleworks.com","company_size":"500+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":333,"name":"Jindal Steel & Power","logo":"https://logo.clearbit.com/jindalsteelpower.com","company_size":"22k+","hiring_category":["Freshers","Experienced"]},
    {"id":334,"name":"JSW Steel","logo":"https://logo.clearbit.com/jsw.in","company_size":"7k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":335,"name":"Jabil","logo":"https://logo.clearbit.com/jabil.com","company_size":"225k+","hiring_category":["Experienced","Internship","Freshers"]},
    {"id":336,"name":"Jfrog","logo":"https://logo.clearbit.com/jfrog.com","company_size":"1.5k+","hiring_category":["Experienced","Internship"]},
    {"id":337,"name":"Jumia","logo":"https://logo.clearbit.com/jumia.com","company_size":"5k+","hiring_category":["Experienced","Freshers"]},
    {"id":338,"name":"Japan Airlines","logo":"https://logo.clearbit.com/jal.co.jp","company_size":"30k+","hiring_category":["Experienced","Freshers"]},
    {"id":339,"name":"Joe & The Juice","logo":"https://logo.clearbit.com/joejuice.com","company_size":"2k+","hiring_category":["Freshers","Experienced"]},
    {"id":340,"name":"Joyson Safety Systems","logo":"https://logo.clearbit.com/joysonsafety.com","company_size":"50k+","hiring_category":["Experienced","Freshers"]},
    {"id":341,"name":"KPMG","logo":"https://logo.clearbit.com/kpmg.com","company_size":"230k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":342,"name":"Kohl's","logo":"https://logo.clearbit.com/kohls.com","company_size":"100k+","hiring_category":["Freshers","Experienced"]},
    {"id":343,"name":"KLA Corporation","logo":"https://logo.clearbit.com/kla.com","company_size":"14k+","hiring_category":["Experienced","Internship","Freshers"]},
    {"id":344,"name":"KFC","logo":"https://logo.clearbit.com/kfc.com","company_size":"800k+","hiring_category":["Freshers","Experienced"]},
    {"id":345,"name":"Kotak Mahindra Bank","logo":"https://logo.clearbit.com/kotak.com","company_size":"70k+","hiring_category":["Freshers","Experienced"]},
    {"id":346,"name":"Kone","logo":"https://logo.clearbit.com/kone.com","company_size":"60k+","hiring_category":["Experienced","Freshers","Internship"]},
    {"id":347,"name":"Kroger","logo":"https://logo.clearbit.com/kroger.com","company_size":"450k+","hiring_category":["Freshers","Experienced"]},
    {"id":348,"name":"Katerra","logo":"https://logo.clearbit.com/katerra.com","company_size":"7k+","hiring_category":["Experienced","Internship"]},
    {"id":349,"name":"Kyndryl","logo":"https://logo.clearbit.com/kyndryl.com","company_size":"90k+","hiring_category":["Freshers","Experienced"]},
    {"id":350,"name":"Kaspersky","logo":"https://logo.clearbit.com/kaspersky.com","company_size":"4k+","hiring_category":["Experienced","Internship","Freshers"]},
    {"id":351,"name":"Kagome","logo":"https://logo.clearbit.com/kagome.co.jp","company_size":"7k+","hiring_category":["Freshers","Experienced"]},
    {"id":352,"name":"Kawasaki Heavy Industries","logo":"https://logo.clearbit.com/khi.co.jp","company_size":"35k+","hiring_category":["Experienced","Freshers"]},
    {"id":353,"name":"Kyndryl India","logo":"https://logo.clearbit.com/kyndryl.com","company_size":"10k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":354,"name":"Kantar","logo":"https://logo.clearbit.com/kantar.com","company_size":"30k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":355,"name":"Kingfisher Airlines","logo":"https://logo.clearbit.com/kingfisherairlines.com","company_size":"5k+","hiring_category":["Experienced","Freshers"]},
    {"id":356,"name":"KEC International","logo":"https://logo.clearbit.com/kecrpg.com","company_size":"8k+","hiring_category":["Freshers","Experienced"]},
    {"id":357,"name":"KPIT Technologies","logo":"https://logo.clearbit.com/kpit.com","company_size":"13k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":358,"name":"Kaleyra","logo":"https://logo.clearbit.com/kaleyra.com","company_size":"400+","hiring_category":["Experienced","Internship","Freshers"]},
    {"id":359,"name":"Knowlarity","logo":"https://logo.clearbit.com/knowlarity.com","company_size":"500+","hiring_category":["Freshers","Experienced"]},
    {"id":360,"name":"Koch Industries","logo":"https://logo.clearbit.com/kochind.com","company_size":"120k+","hiring_category":["Experienced","Freshers"]},
    {"id":361,"name":"Larsen & Toubro (L&T)","logo":"https://logo.clearbit.com/larsentoubro.com","company_size":"90k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":362,"name":"LinkedIn","logo":"https://logo.clearbit.com/linkedin.com","company_size":"20k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":363,"name":"Lenovo","logo":"https://logo.clearbit.com/lenovo.com","company_size":"77k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":364,"name":"LG Electronics","logo":"https://logo.clearbit.com/lg.com","company_size":"75k+","hiring_category":["Freshers","Experienced"]},
    {"id":365,"name":"L&T Infotech (LTIMindtree)","logo":"https://logo.clearbit.com/ltimindtree.com","company_size":"82k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":366,"name":"L'Oreal","logo":"https://logo.clearbit.com/loreal.com","company_size":"88k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":367,"name":"Lucid Motors","logo":"https://logo.clearbit.com/lucidmotors.com","company_size":"6k+","hiring_category":["Experienced","Internship"]},
    {"id":368,"name":"Lionbridge","logo":"https://logo.clearbit.com/lionbridge.com","company_size":"5k+","hiring_category":["Freshers","Experienced"]},
    {"id":369,"name":"Lenskart","logo":"https://logo.clearbit.com/lenskart.com","company_size":"5k+","hiring_category":["Freshers","Experienced"]},
    {"id":370,"name":"Levi Strauss & Co.","logo":"https://logo.clearbit.com/levi.com","company_size":"16k+","hiring_category":["Freshers","Experienced"]},
    {"id":371,"name":"LBBW Bank","logo":"https://logo.clearbit.com/lbbw.de","company_size":"10k+","hiring_category":["Experienced","Internship"]},
    {"id":372,"name":"Labcorp","logo":"https://logo.clearbit.com/labcorp.com","company_size":"60k+","hiring_category":["Experienced","Freshers"]},
    {"id":373,"name":"Lam Research","logo":"https://logo.clearbit.com/lamresearch.com","company_size":"19k+","hiring_category":["Internship","Experienced"]},
    {"id":374,"name":"Landmark Group","logo":"https://logo.clearbit.com/landmarkgroup.com","company_size":"50k+","hiring_category":["Freshers","Experienced"]},
    {"id":375,"name":"London Stock Exchange Group (LSEG)","logo":"https://logo.clearbit.com/lseg.com","company_size":"26k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":376,"name":"LTI Mindtree (duplicate removed, extension roles)","logo":"https://logo.clearbit.com/ltimindtree.com","company_size":"82k+","hiring_category":["Freshers","Experienced"]},
    {"id":377,"name":"Licious","logo":"https://logo.clearbit.com/licious.in","company_size":"5k+","hiring_category":["Freshers","Experienced"]},
    {"id":378,"name":"Lupin Pharmaceuticals","logo":"https://logo.clearbit.com/lupin.com","company_size":"20k+","hiring_category":["Freshers","Experienced"]},
    {"id":379,"name":"Luxoft","logo":"https://logo.clearbit.com/luxoft.com","company_size":"17k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":380,"name":"Lamudi","logo":"https://logo.clearbit.com/lamudi.com","company_size":"1k+","hiring_category":["Experienced","Internship"]},
    {"id":381,"name":"Microsoft","logo":"https://logo.clearbit.com/microsoft.com","company_size":"220k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":382,"name":"Meta (Facebook)","logo":"https://logo.clearbit.com/meta.com","company_size":"90k+","hiring_category":["Internship","Experienced"]},
    {"id":383,"name":"Mindtree (now LTIMindtree)","logo":"https://logo.clearbit.com/mindtree.com","company_size":"38k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":384,"name":"Micron Technology","logo":"https://logo.clearbit.com/micron.com","company_size":"43k+","hiring_category":["Internship","Experienced","Freshers"]},
    {"id":385,"name":"Mercedes-Benz","logo":"https://logo.clearbit.com/mercedes-benz.com","company_size":"170k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":386,"name":"Mastercard","logo":"https://logo.clearbit.com/mastercard.com","company_size":"30k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":387,"name":"Myntra","logo":"https://logo.clearbit.com/myntra.com","company_size":"5k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":388,"name":"McKinsey & Company","logo":"https://logo.clearbit.com/mckinsey.com","company_size":"45k+","hiring_category":["Freshers","Experienced"]},
    {"id":389,"name":"Moody's","logo":"https://logo.clearbit.com/moodys.com","company_size":"15k+","hiring_category":["Internship","Experienced"]},
    {"id":390,"name":"MongoDB","logo":"https://logo.clearbit.com/mongodb.com","company_size":"5k+","hiring_category":["Internship","Experienced"]},
    {"id":391,"name":"Micromax","logo":"https://logo.clearbit.com/micromaxinfo.com","company_size":"2k+","hiring_category":["Experienced","Freshers"]},
    {"id":392,"name":"Mphasis","logo":"https://logo.clearbit.com/mphasis.com","company_size":"30k+","hiring_category":["Freshers","Experienced"]},
    {"id":393,"name":"Medtronic","logo":"https://logo.clearbit.com/medtronic.com","company_size":"95k+","hiring_category":["Experienced","Internship"]},
    {"id":394,"name":"Meesho","logo":"https://logo.clearbit.com/meesho.com","company_size":"3k+","hiring_category":["Freshers","Experienced"]},
    {"id":395,"name":"Microchip Technology","logo":"https://logo.clearbit.com/microchip.com","company_size":"20k+","hiring_category":["Internship","Experienced"]},
    {"id":396,"name":"Motorola Solutions","logo":"https://logo.clearbit.com/motorolasolutions.com","company_size":"18k+","hiring_category":["Experienced","Internship"]},
    {"id":397,"name":"Morgan Stanley","logo":"https://logo.clearbit.com/morganstanley.com","company_size":"80k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":398,"name":"Muthoot Finance","logo":"https://logo.clearbit.com/muthootfinance.com","company_size":"30k+","hiring_category":["Freshers","Experienced"]},
    {"id":399,"name":"Maruti Suzuki","logo":"https://logo.clearbit.com/marutisuzuki.com","company_size":"40k+","hiring_category":["Freshers","Experienced"]},
    {"id":400,"name":"Maersk","logo":"https://logo.clearbit.com/maersk.com","company_size":"100k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":401,"name":"Nvidia","logo":"https://logo.clearbit.com/nvidia.com","company_size":"25k+","hiring_category":["Internship","Experienced","Freshers"]},
    {"id":402,"name":"Nokia","logo":"https://logo.clearbit.com/nokia.com","company_size":"90k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":403,"name":"Netflix","logo":"https://logo.clearbit.com/netflix.com","company_size":"12k+","hiring_category":["Internship","Experienced"]},
    {"id":404,"name":"Nestle","logo":"https://logo.clearbit.com/nestle.com","company_size":"300k+","hiring_category":["Freshers","Experienced"]},
    {"id":405,"name":"Nomura","logo":"https://logo.clearbit.com/nomura.com","company_size":"30k+","hiring_category":["Experienced","Freshers"]},
    {"id":406,"name":"Novartis","logo":"https://logo.clearbit.com/novartis.com","company_size":"110k+","hiring_category":["Experienced","Internship"]},
    {"id":407,"name":"Nokia Networks","logo":"https://logo.clearbit.com/networks.nokia.com","company_size":"80k+","hiring_category":["Freshers","Experienced"]},
    {"id":408,"name":"Nutricia","logo":"https://logo.clearbit.com/nutricia.com","company_size":"5k+","hiring_category":["Freshers","Experienced"]},
    {"id":409,"name":"NXP Semiconductors","logo":"https://logo.clearbit.com/nxp.com","company_size":"30k+","hiring_category":["Internship","Experienced"]},
    {"id":410,"name":"Nagarro","logo":"https://logo.clearbit.com/nagarro.com","company_size":"20k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":411,"name":"NetApp","logo":"https://logo.clearbit.com/netapp.com","company_size":"13k+","hiring_category":["Internship","Experienced"]},
    {"id":412,"name":"Neudesic","logo":"https://logo.clearbit.com/neudesic.com","company_size":"2k+","hiring_category":["Freshers","Experienced"]},
    {"id":413,"name":"Nio","logo":"https://logo.clearbit.com/nio.com","company_size":"7k+","hiring_category":["Freshers","Experienced"]},
    {"id":414,"name":"Nordea","logo":"https://logo.clearbit.com/nordea.com","company_size":"30k+","hiring_category":["Experienced","Freshers"]},
    {"id":415,"name":"Novell","logo":"https://logo.clearbit.com/novell.com","company_size":"2k+","hiring_category":["Freshers","Experienced"]},
    {"id":416,"name":"Newgen Software","logo":"https://logo.clearbit.com/newgensoft.com","company_size":"5k+","hiring_category":["Freshers","Experienced"]},
    {"id":417,"name":"NortonLifeLock","logo":"https://logo.clearbit.com/nortonlifelock.com","company_size":"4k+","hiring_category":["Experienced","Internship"]},
    {"id":418,"name":"NextEra Energy","logo":"https://logo.clearbit.com/nexteraenergy.com","company_size":"15k+","hiring_category":["Experienced"]},
    {"id":419,"name":"NVIDIA AI","logo":"https://logo.clearbit.com/nvidia.com","company_size":"25k+","hiring_category":["Internship","Experienced"]},
    {"id":420,"name":"NetEase","logo":"https://logo.clearbit.com/netease.com","company_size":"50k+","hiring_category":["Freshers","Experienced"]},
    {"id":421,"name":"Oracle","logo":"https://logo.clearbit.com/oracle.com","company_size":"140k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":422,"name":"Optum","logo":"https://logo.clearbit.com/optum.com","company_size":"200k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":423,"name":"OpenText","logo":"https://logo.clearbit.com/opentext.com","company_size":"14k+","hiring_category":["Freshers","Experienced"]},
    {"id":424,"name":"Ola","logo":"https://logo.clearbit.com/olacabs.com","company_size":"15k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":425,"name":"Okta","logo":"https://logo.clearbit.com/okta.com","company_size":"5k+","hiring_category":["Internship","Experienced"]},
    {"id":426,"name":"OpenAI","logo":"https://logo.clearbit.com/openai.com","company_size":"2k+","hiring_category":["Internship","Experienced"]},
    {"id":427,"name":"OnePlus","logo":"https://logo.clearbit.com/oneplus.com","company_size":"5k+","hiring_category":["Freshers","Experienced"]},
    {"id":428,"name":"OYO Rooms","logo":"https://logo.clearbit.com/oyorooms.com","company_size":"20k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":429,"name":"Optimizely","logo":"https://logo.clearbit.com/optimizely.com","company_size":"1k+","hiring_category":["Internship","Experienced"]},
    {"id":430,"name":"Okaya Power","logo":"https://logo.clearbit.com/okayapower.com","company_size":"1k+","hiring_category":["Freshers","Experienced"]},
    {"id":431,"name":"Oppo","logo":"https://logo.clearbit.com/oppo.com","company_size":"40k+","hiring_category":["Freshers","Experienced"]},
    {"id":432,"name":"Olympus Corporation","logo":"https://logo.clearbit.com/olympus-global.com","company_size":"30k+","hiring_category":["Experienced","Freshers"]},
    {"id":433,"name":"Omnicom Group","logo":"https://logo.clearbit.com/omnicomgroup.com","company_size":"70k+","hiring_category":["Experienced","Freshers"]},
    {"id":434,"name":"ON Semiconductor","logo":"https://logo.clearbit.com/onsemi.com","company_size":"30k+","hiring_category":["Freshers","Experienced"]},
    {"id":435,"name":"Ola Electric","logo":"https://logo.clearbit.com/olaelectric.com","company_size":"5k+","hiring_category":["Freshers","Experienced"]},
    {"id":436,"name":"Ola Mobility","logo":"https://logo.clearbit.com/olamobility.com","company_size":"2k+","hiring_category":["Freshers","Experienced"]},
    {"id":437,"name":"Otis Elevator","logo":"https://logo.clearbit.com/otis.com","company_size":"70k+","hiring_category":["Experienced","Freshers"]},
    {"id":438,"name":"One Horizon Group","logo":"https://logo.clearbit.com/onehorizon.com","company_size":"1k+","hiring_category":["Freshers","Experienced"]},
    {"id":439,"name":"Opto Circuits","logo":"https://logo.clearbit.com/opto-circuits.com","company_size":"3k+","hiring_category":["Freshers","Experienced"]},
    {"id":440,"name":"OYO Workspaces","logo":"https://logo.clearbit.com/oyoworkspaces.com","company_size":"2k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":441,"name":"PayPal","logo":"https://logo.clearbit.com/paypal.com","company_size":"30k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":442,"name":"Pinterest","logo":"https://logo.clearbit.com/pinterest.com","company_size":"3k+","hiring_category":["Internship","Experienced"]},
    {"id":443,"name":"Pfizer","logo":"https://logo.clearbit.com/pfizer.com","company_size":"80k+","hiring_category":["Experienced","Freshers"]},
    {"id":444,"name":"Philips","logo":"https://logo.clearbit.com/philips.com","company_size":"80k+","hiring_category":["Experienced","Freshers"]},
    {"id":445,"name":"PWC","logo":"https://logo.clearbit.com/pwc.com","company_size":"295k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":446,"name":"Procter & Gamble","logo":"https://logo.clearbit.com/pg.com","company_size":"97k+","hiring_category":["Freshers","Experienced"]},
    {"id":447,"name":"Polaris Consulting","logo":"https://logo.clearbit.com/polarisconsulting.com","company_size":"10k+","hiring_category":["Freshers","Experienced"]},
    {"id":448,"name":"Postman","logo":"https://logo.clearbit.com/postman.com","company_size":"1.5k+","hiring_category":["Internship","Experienced"]},
    {"id":449,"name":"Paytm","logo":"https://logo.clearbit.com/paytm.com","company_size":"25k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":450,"name":"Ping Identity","logo":"https://logo.clearbit.com/pingidentity.com","company_size":"2k+","hiring_category":["Experienced","Internship"]},
    {"id":451,"name":"PepsiCo","logo":"https://logo.clearbit.com/pepsico.com","company_size":"300k+","hiring_category":["Experienced","Freshers"]},
    {"id":452,"name":"Petrofac","logo":"https://logo.clearbit.com/petrofac.com","company_size":"15k+","hiring_category":["Experienced","Freshers"]},
    {"id":453,"name":"Presto Engineering","logo":"https://logo.clearbit.com/prestoengineering.com","company_size":"1k+","hiring_category":["Freshers","Experienced"]},
    {"id":454,"name":"Palo Alto Networks","logo":"https://logo.clearbit.com/paloaltonetworks.com","company_size":"10k+","hiring_category":["Internship","Experienced"]},
    {"id":455,"name":"Proofpoint","logo":"https://logo.clearbit.com/proofpoint.com","company_size":"5k+","hiring_category":["Experienced","Internship"]},
    {"id":456,"name":"Ping An Technology","logo":"https://logo.clearbit.com/pingan.com","company_size":"50k+","hiring_category":["Experienced","Freshers"]},
    {"id":457,"name":"Parker Hannifin","logo":"https://logo.clearbit.com/parker.com","company_size":"60k+","hiring_category":["Experienced","Freshers"]},
    {"id":458,"name":"Penta Security","logo":"https://logo.clearbit.com/pentasecurity.com","company_size":"1k+","hiring_category":["Experienced","Freshers"]},
    {"id":459,"name":"Practo","logo":"https://logo.clearbit.com/practo.com","company_size":"2k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":460,"name":"PubMatic","logo":"https://logo.clearbit.com/pubmatic.com","company_size":"1k+","hiring_category":["Internship","Experienced"]},
    {"id":461,"name":"Qualcomm","logo":"https://logo.clearbit.com/qualcomm.com","company_size":"45k+","hiring_category":["Internship","Experienced","Freshers"]},
    {"id":462,"name":"QuEST Global","logo":"https://logo.clearbit.com/quest-global.com","company_size":"15k+","hiring_category":["Freshers","Experienced"]},
    {"id":463,"name":"Quick Heal","logo":"https://logo.clearbit.com/quickheal.com","company_size":"2k+","hiring_category":["Freshers","Experienced"]},
    {"id":464,"name":"Quikr","logo":"https://logo.clearbit.com/quikr.com","company_size":"1k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":465,"name":"Quora","logo":"https://logo.clearbit.com/quora.com","company_size":"1k+","hiring_category":["Internship","Experienced"]},
    {"id":466,"name":"Qlik","logo":"https://logo.clearbit.com/qlik.com","company_size":"3k+","hiring_category":["Experienced","Freshers"]},
    {"id":467,"name":"Quantiphi","logo":"https://logo.clearbit.com/quantiphi.com","company_size":"1.5k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":468,"name":"QuintilesIMS (IQVIA)","logo":"https://logo.clearbit.com/iqvia.com","company_size":"70k+","hiring_category":["Experienced","Freshers"]},
    {"id":469,"name":"Qubole","logo":"https://logo.clearbit.com/qubole.com","company_size":"500+","hiring_category":["Internship","Experienced"]},
    {"id":470,"name":"Quest Diagnostics","logo":"https://logo.clearbit.com/questdiagnostics.com","company_size":"45k+","hiring_category":["Experienced","Freshers"]},
    {"id":471,"name":"Razorpay","logo":"https://logo.clearbit.com/razorpay.com","company_size":"2k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":472,"name":"Reliance Industries","logo":"https://logo.clearbit.com/relianceindustries.com","company_size":"200k+","hiring_category":["Freshers","Experienced"]},
    {"id":473,"name":"Red Hat","logo":"https://logo.clearbit.com/redhat.com","company_size":"14k+","hiring_category":["Internship","Experienced","Freshers"]},
    {"id":474,"name":"Rakuten","logo":"https://logo.clearbit.com/rakuten.com","company_size":"15k+","hiring_category":["Experienced","Freshers"]},
    {"id":475,"name":"Robert Bosch","logo":"https://logo.clearbit.com/bosch.com","company_size":"400k+","hiring_category":["Freshers","Experienced"]},
    {"id":476,"name":"Rubrik","logo":"https://logo.clearbit.com/rubrik.com","company_size":"3k+","hiring_category":["Internship","Experienced"]},
    {"id":477,"name":"Rivigo","logo":"https://logo.clearbit.com/rivigo.com","company_size":"5k+","hiring_category":["Freshers","Experienced"]},
    {"id":478,"name":"RingCentral","logo":"https://logo.clearbit.com/ringcentral.com","company_size":"6k+","hiring_category":["Internship","Experienced"]},
    {"id":479,"name":"Royal Enfield","logo":"https://logo.clearbit.com/royalenfield.com","company_size":"20k+","hiring_category":["Freshers","Experienced"]},
    {"id":480,"name":"RazorThink","logo":"https://logo.clearbit.com/razorthink.com","company_size":"500+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":481,"name":"Salesforce","logo":"https://logo.clearbit.com/salesforce.com","company_size":"70k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":482,"name":"Samsung","logo":"https://logo.clearbit.com/samsung.com","company_size":"320k+","hiring_category":["Freshers","Experienced"]},
    {"id":483,"name":"SAP","logo":"https://logo.clearbit.com/sap.com","company_size":"105k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":484,"name":"Siemens","logo":"https://logo.clearbit.com/siemens.com","company_size":"300k+","hiring_category":["Freshers","Experienced"]},
    {"id":485,"name":"Shopify","logo":"https://logo.clearbit.com/shopify.com","company_size":"10k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":486,"name":"Snapdeal","logo":"https://logo.clearbit.com/snapdeal.com","company_size":"5k+","hiring_category":["Freshers","Experienced"]},
    {"id":487,"name":"Spotify","logo":"https://logo.clearbit.com/spotify.com","company_size":"8k+","hiring_category":["Internship","Experienced"]},
    {"id":488,"name":"Square","logo":"https://logo.clearbit.com/squareup.com","company_size":"6k+","hiring_category":["Internship","Experienced","Freshers"]},
    {"id":489,"name":"Swiggy","logo":"https://logo.clearbit.com/swiggy.com","company_size":"15k+","hiring_category":["Freshers","Experienced"]},
    {"id":490,"name":"Scribd","logo":"https://logo.clearbit.com/scribd.com","company_size":"400+","hiring_category":["Internship","Experienced"]},
    {"id":491,"name":"Tata Consultancy Services (TCS)","logo":"https://logo.clearbit.com/tcs.com","company_size":"500k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":492,"name":"Tata Motors","logo":"https://logo.clearbit.com/tatamotors.com","company_size":"70k+","hiring_category":["Freshers","Experienced"]},
    {"id":493,"name":"Target","logo":"https://logo.clearbit.com/target.com","company_size":"450k+","hiring_category":["Freshers","Experienced"]},
    {"id":494,"name":"Tesla","logo":"https://logo.clearbit.com/tesla.com","company_size":"120k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":495,"name":"TikTok","logo":"https://logo.clearbit.com/tiktok.com","company_size":"100k+","hiring_category":["Internship","Experienced"]},
    {"id":496,"name":"ThoughtWorks","logo":"https://logo.clearbit.com/thoughtworks.com","company_size":"12k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":497,"name":"Toast","logo":"https://logo.clearbit.com/toasttab.com","company_size":"5k+","hiring_category":["Internship","Experienced"]},
    {"id":498,"name":"Trello","logo":"https://logo.clearbit.com/trello.com","company_size":"500+","hiring_category":["Internship","Experienced"]},
    {"id":499,"name":"Truist Financial","logo":"https://logo.clearbit.com/truist.com","company_size":"50k+","hiring_category":["Freshers","Experienced"]},
    {"id":500,"name":"Twilio","logo":"https://logo.clearbit.com/twilio.com","company_size":"7k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":501,"name":"Uber","logo":"https://logo.clearbit.com/uber.com","company_size":"30k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":502,"name":"Unacademy","logo":"https://logo.clearbit.com/unacademy.com","company_size":"3k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":503,"name":"Unilever","logo":"https://logo.clearbit.com/unilever.com","company_size":"150k+","hiring_category":["Freshers","Experienced"]},
    {"id":504,"name":"Upstox","logo":"https://logo.clearbit.com/upstox.com","company_size":"1k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":505,"name":"UiPath","logo":"https://logo.clearbit.com/uipath.com","company_size":"9k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":506,"name":"VMware","logo":"https://logo.clearbit.com/vmware.com","company_size":"35k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":507,"name":"Volvo","logo":"https://logo.clearbit.com/volvo.com","company_size":"100k+","hiring_category":["Freshers","Experienced"]},
    {"id":508,"name":"Visa","logo":"https://logo.clearbit.com/visa.com","company_size":"20k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":509,"name":"Vistaprint","logo":"https://logo.clearbit.com/vistaprint.com","company_size":"7k+","hiring_category":["Internship","Experienced"]},
    {"id":510,"name":"Vodafone","logo":"https://logo.clearbit.com/vodafone.com","company_size":"100k+","hiring_category":["Freshers","Experienced"]},
    {"id":511,"name":"Walmart","logo":"https://logo.clearbit.com/walmart.com","company_size":"2.3M+","hiring_category":["Freshers","Experienced"]},
    {"id":512,"name":"Wipro","logo":"https://logo.clearbit.com/wipro.com","company_size":"220k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":513,"name":"Wayfair","logo":"https://logo.clearbit.com/wayfair.com","company_size":"16k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":514,"name":"Western Digital","logo":"https://logo.clearbit.com/westerndigital.com","company_size":"60k+","hiring_category":["Freshers","Experienced"]},
    {"id":515,"name":"Workday","logo":"https://logo.clearbit.com/workday.com","company_size":"15k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":516,"name":"Xiaomi","logo":"https://logo.clearbit.com/mi.com","company_size":"25k+","hiring_category":["Freshers","Experienced"]},
    {"id":517,"name":"Xerox","logo":"https://logo.clearbit.com/xerox.com","company_size":"30k+","hiring_category":["Freshers","Experienced"]},
    {"id":518,"name":"Xapo","logo":"https://logo.clearbit.com/xapo.com","company_size":"500+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":519,"name":"Yahoo","logo":"https://logo.clearbit.com/yahoo.com","company_size":"9k+","hiring_category":["Experienced","Internship"]},
    {"id":520,"name":"Yelp","logo":"https://logo.clearbit.com/yelp.com","company_size":"6k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":521,"name":"YouTube","logo":"https://logo.clearbit.com/youtube.com","company_size":"25k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":522,"name":"Yatra","logo":"https://logo.clearbit.com/yatra.com","company_size":"1k+","hiring_category":["Freshers","Experienced"]},
    {"id":523,"name":"Zoom","logo":"https://logo.clearbit.com/zoom.us","company_size":"7k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":524,"name":"Zomato","logo":"https://logo.clearbit.com/zomato.com","company_size":"8k+","hiring_category":["Freshers","Experienced"]},
    {"id":525,"name":"Zebra Technologies","logo":"https://logo.clearbit.com/zebra.com","company_size":"8k+","hiring_category":["Freshers","Experienced"]},
    {"id":526,"name":"Zendesk","logo":"https://logo.clearbit.com/zendesk.com","company_size":"6k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":527,"name":"Zoho","logo":"https://logo.clearbit.com/zoho.com","company_size":"15k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":528,"name":"IBM","logo":"https://logo.clearbit.com/ibm.com","company_size":"300k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":529,"name":"Infosys","logo":"https://logo.clearbit.com/infosys.com","company_size":"330k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":530,"name":"Intel","logo":"https://logo.clearbit.com/intel.com","company_size":"120k+","hiring_category":["Internship","Freshers","Experienced"]},
    {"id":531,"name":"ICICI Bank","logo":"https://logo.clearbit.com/icicibank.com","company_size":"100k+","hiring_category":["Freshers","Experienced"]},
    {"id":532,"name":"IKEA","logo":"https://logo.clearbit.com/ikea.com","company_size":"220k+","hiring_category":["Freshers","Experienced"]},
    {"id":533,"name":"IndiGo Airlines","logo":"https://logo.clearbit.com/goindigo.in","company_size":"23k+","hiring_category":["Freshers","Experienced"]},
    {"id":534,"name":"InMobi","logo":"https://logo.clearbit.com/inmobi.com","company_size":"2.5k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":535,"name":"IHG Hotels & Resorts","logo":"https://logo.clearbit.com/ihg.com","company_size":"30k+","hiring_category":["Freshers","Experienced"]},
    {"id":536,"name":"ITC Limited","logo":"https://logo.clearbit.com/itcportal.com","company_size":"36k+","hiring_category":["Freshers","Experienced"]},
    {"id":537,"name":"Infosys BPM","logo":"https://logo.clearbit.com/infosysbpm.com","company_size":"45k+","hiring_category":["Freshers","Experienced"]},
    {"id":538,"name":"Icertis","logo":"https://logo.clearbit.com/icertis.com","company_size":"2k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":539,"name":"ION Group","logo":"https://logo.clearbit.com/iongroup.com","company_size":"10k+","hiring_category":["Experienced","Internship"]},
    {"id":540,"name":"Itron","logo":"https://logo.clearbit.com/itron.com","company_size":"7k+","hiring_category":["Experienced","Freshers"]},
    {"id":541,"name":"Imperial College Healthcare","logo":"https://logo.clearbit.com/imperial.nhs.uk","company_size":"14k+","hiring_category":["Experienced"]},
    {"id":542,"name":"IndiaMART","logo":"https://logo.clearbit.com/indiamart.com","company_size":"5k+","hiring_category":["Freshers","Experienced"]},
    {"id":543,"name":"IRCTC","logo":"https://logo.clearbit.com/irctc.co.in","company_size":"5k+","hiring_category":["Freshers","Experienced"]},
    {"id":544,"name":"IAC","logo":"https://logo.clearbit.com/iac.com","company_size":"10k+","hiring_category":["Experienced"]},
    {"id":545,"name":"Illumina","logo":"https://logo.clearbit.com/illumina.com","company_size":"9k+","hiring_category":["Experienced","Internship"]},
    {"id":546,"name":"Impetus","logo":"https://logo.clearbit.com/impetus.com","company_size":"3k+","hiring_category":["Freshers","Experienced"]},
    {"id":547,"name":"Infineon Technologies","logo":"https://logo.clearbit.com/infineon.com","company_size":"56k+","hiring_category":["Internship","Experienced"]},
    {"id":548,"name":"Informatica","logo":"https://logo.clearbit.com/informatica.com","company_size":"5k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":549,"name":"Intercontinental Exchange","logo":"https://logo.clearbit.com/theice.com","company_size":"9k+","hiring_category":["Experienced","Internship"]},
    {"id":550,"name":"Incedo","logo":"https://logo.clearbit.com/incedoinc.com","company_size":"3k+","hiring_category":["Freshers","Experienced"]},
    {"id":551,"name":"Intuit","logo":"https://logo.clearbit.com/intuit.com","company_size":"17k+","hiring_category":["Internship","Experienced","Freshers"]},
    {"id":552,"name":"IHS Markit (S&P Global)","logo":"https://logo.clearbit.com/spglobal.com","company_size":"35k+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":553,"name":"Iron Mountain","logo":"https://logo.clearbit.com/ironmountain.com","company_size":"25k+","hiring_category":["Experienced"]},
    {"id":554,"name":"Itron Networked Solutions","logo":"https://logo.clearbit.com/itron.com","company_size":"1k+","hiring_category":["Experienced"]},
    {"id":555,"name":"India Post Payments Bank","logo":"https://logo.clearbit.com/ippbonline.com","company_size":"10k+","hiring_category":["Freshers","Experienced"]},
    {"id":556,"name":"IndusInd Bank","logo":"https://logo.clearbit.com/indusind.com","company_size":"30k+","hiring_category":["Freshers","Experienced"]},
    {"id":557,"name":"Incredible Technologies","logo":"https://logo.clearbit.com/itsgames.com","company_size":"500+","hiring_category":["Experienced","Internship"]},
    {"id":558,"name":"Infosec Ventures","logo":"https://logo.clearbit.com/infosecventures.com","company_size":"200+","hiring_category":["Freshers","Experienced"]},
    {"id":559,"name":"iMerit","logo":"https://logo.clearbit.com/imerit.net","company_size":"4k+","hiring_category":["Freshers","Experienced"]},
    {"id":560,"name":"Immersion","logo":"https://logo.clearbit.com/immersion.com","company_size":"200+","hiring_category":["Experienced","Internship"]},
    {"id":561,"name":"Improbable","logo":"https://logo.clearbit.com/improbable.io","company_size":"600+","hiring_category":["Internship","Experienced"]},
    {"id":562,"name":"India Today Group","logo":"https://logo.clearbit.com/indiatoday.in","company_size":"3k+","hiring_category":["Freshers","Experienced"]},
    {"id":563,"name":"InShorts","logo":"https://logo.clearbit.com/inshorts.com","company_size":"400+","hiring_category":["Freshers","Experienced"]},
    {"id":564,"name":"Ivy Comptech","logo":"https://logo.clearbit.com/ivyglobal.com","company_size":"2k+","hiring_category":["Freshers","Experienced"]},
    {"id":565,"name":"Inkitt","logo":"https://logo.clearbit.com/inkitt.com","company_size":"200+","hiring_category":["Experienced","Internship"]},
    {"id":566,"name":"Incedius Consulting","logo":"https://logo.clearbit.com/incedius.com","company_size":"200+","hiring_category":["Freshers","Experienced"]},
    {"id":567,"name":"IOTech Systems","logo":"https://logo.clearbit.com/iotechsys.com","company_size":"100+","hiring_category":["Internship","Experienced"]},
    {"id":568,"name":"Iris Software","logo":"https://logo.clearbit.com/irissoftware.com","company_size":"4k+","hiring_category":["Freshers","Experienced"]},
    {"id":569,"name":"Intelliswift Software","logo":"https://logo.clearbit.com/intelliswift.com","company_size":"3k+","hiring_category":["Freshers","Experienced"]},
    {"id":570,"name":"Infinite Computer Solutions","logo":"https://logo.clearbit.com/infinite.com","company_size":"10k+","hiring_category":["Freshers","Experienced"]},
    {"id":571,"name":"Incedo Healthcare","logo":"https://logo.clearbit.com/incedoinc.com","company_size":"1k+","hiring_category":["Experienced"]},
    {"id":572,"name":"iMocha","logo":"https://logo.clearbit.com/imocha.io","company_size":"200+","hiring_category":["Freshers","Experienced"]},
    {"id":573,"name":"IdeaForge","logo":"https://logo.clearbit.com/ideaforge.co.in","company_size":"400+","hiring_category":["Freshers","Experienced","Internship"]},
    {"id":574,"name":"Indus OS","logo":"https://logo.clearbit.com/indusos.com","company_size":"200+","hiring_category":["Experienced","Internship"]},
    {"id":575,"name":"INOX Air Products","logo":"https://logo.clearbit.com/inoxairproducts.com","company_size":"3k+","hiring_category":["Freshers","Experienced"]},
    {"id":576,"name":"Instacart","logo":"https://logo.clearbit.com/instacart.com","company_size":"5k+","hiring_category":["Internship","Experienced"]},
    {"id":577,"name":"InstaMojo","logo":"https://logo.clearbit.com/instamojo.com","company_size":"200+","hiring_category":["Freshers","Experienced"]},
]
export default companies;